### ISSUE TITLE
Render image tags

### ISSUE THREAD

**Issue by niloch** [simonw/datasette-render-markdown#10]
Is there a way for this support rendering images so they appear like `datasette-render-images` but using the markdown syntax `![Alt Text](path/to/image.jpg)`?  Right now for me, the table view displays the raw html `<img alt="" src="/path/to/image.jpg">` without rendering the image itself.

Or is this a case where I'd be better of downloading all those images locally and using `datasette-render-images`?

**Comment by simonw** [comment]
I don't see any reason not to support regular markdown images. The reason they don't work now is that Bleach is stripping them out: https://github.com/simonw/datasette-render-markdown/blob/362f7816545598d35e3d4b34e27975ab33b0bc4a/datasette_render_markdown/__init__.py#L44-L74

**Comment by simonw** [comment]
I'm going to add `style="max-width: 100%"` to the image tags.

**Comment by simonw** [comment]
I'm going to re-release this as 2.0 and withdraw that 1.3 release, since this should be considered a breaking change.

**Comment by simonw** [comment]
I yanked the release on PyPI:

<img width="428" alt="Manage__datasette-render-markdown__releases_·_PyPI" src="https://user-images.githubusercontent.com/9599/134429328-115d2bb5-2418-4b70-ab33-1d17117ac859.png">

**Comment by simonw** [comment]
Released as 2.0 here: https://pypi.org/project/datasette-render-markdown/2.0/
