### ISSUE TITLE
Markdown renders with lots of vertical white space

### ISSUE THREAD

**Issue by garethr** [simonw/datasette-render-markdown#7]
The plugin renders markdown with lots of extra vertical white space. eg.

![Screenshot 2020-09-27 at 08 55 32](https://user-images.githubusercontent.com/2029/94359496-7ce34000-009f-11eb-835c-0accff31b481.png)

Note this is just a set of titles, paragraphs and lists. No blank paragraphs or line breaks.

The culprit appears to be the CSS, specifically:

```css
white-space: pre-wrap;
```

Removing that rule, renders as I'd expect without the additional vertical space.

![Screenshot 2020-09-27 at 08 55 17](https://user-images.githubusercontent.com/2029/94359495-7bb21300-009f-11eb-9c8a-ea410529fd96.png)

**Comment by simonw** [comment]
This was fixed in #9.
